version: '3.9'

services:
  main-app:
    container_name: main_app
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../pychats/application/:/app
    command: "uvicorn pychats:application:api:main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env

